import { useState } from 'react';
import { BookOpen, CheckCircle2, MapPin, Save, Users } from 'lucide-react';
import Layout from './components/Layout';
import { Actions, Check, Field } from './components/Fields';
import { useSurvey } from './hooks/useSurvey';
import stores from './data/stores.json';
import options from './data/options.json';
const mainTitle='書店 9 月課程提報與同仁職類調查';
export default function App(){
 const {data,update,reset}=useSurvey(); const [error,setError]=useState(''); const go=step=>{update({step});window.scrollTo({top:0,behavior:'smooth'})};
 const store=stores.find(s=>s.id===data.storeId);
 if(data.step===1)return <Layout step={1} title={mainTitle} description={<><p>為提升同仁實務應用能力，9 月將開設「書店法律實務案例研討」及「包裝技巧」課程，請店主管依序完成上課學員提報。</p><p>此外，請同步填寫門市同仁所屬業管區域，以利依同仁專業類別進行課程調訓，逐步建立更完整的培訓機制。</p></>}><div className="welcome-grid"><Info icon={BookOpen} title="課程提報" text="法律實務及包裝技巧課程"/><Info icon={Users} title="職類調查" text="門市同仁所屬業管區域"/><Info icon={Save} title="自動儲存" text="可放心返回修改填寫內容"/></div><Actions next={()=>go(2)} nextLabel="開始填寫"/></Layout>;
 if(data.step===2)return <Layout step={2} title={mainTitle} onBack={()=>go(1)} description="請先選取您所屬的店別，後續頁面將自動帶入該店同仁資料。"><Field label="請選取所屬店別" required error={error}><select value={data.storeId} onChange={e=>{update({storeId:e.target.value,roles:{}});setError('')}}><option value="">請選擇店別</option>{stores.map(s=><option key={s.id} value={s.id}>{s.id} {s.name}</option>)}</select></Field><Actions back={()=>go(1)} next={()=>data.storeId?go(3):setError('請選擇店別')} nextLabel="繼續，進入法律實務課程提報"/></Layout>;
 if(data.step===3){const setLegal=p=>update({legal:{...data.legal,...p}});return <Layout step={3} title="書店法律實務課程" onBack={()=>go(2)} description={<>9 月共計三個場次，課程時間皆為 <b>14:00–18:00</b>。店主管／組長已列入調訓名單，請依門市需求提報其他參訓學員。</>}><StoreTag store={store}/><div className="section-title">新增參訓人員</div>{data.legal.people.map((p,i)=><div className="person-row" key={i}><Field label="姓名"><input disabled={data.legal.none} value={p.name} placeholder="請輸入同仁姓名" onChange={e=>setLegal({people:[{...p,name:e.target.value}]})}/></Field><Field label="場次"><select disabled={data.legal.none} value={p.session} onChange={e=>setLegal({people:[{...p,session:e.target.value}]})}><option value="">請選擇場次</option>{options.legalSessions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="參訓場次需求"><input disabled={data.legal.none} value={p.need} placeholder="如：僅能參加視訊場" onChange={e=>setLegal({people:[{...p,need:e.target.value}]})}/></Field></div>)}<div className="none-row"><Check label="無須新增參訓人員" checked={data.legal.none} onChange={none=>setLegal({none})}/></div><Actions back={()=>go(2)} next={()=>go(4)} nextLabel="繼續，進入包裝技巧課程提報"/></Layout>}
 if(data.step===4){const setPack=p=>update({packaging:{...data.packaging,...p}});return <Layout step={4} title="包裝技巧課程" onBack={()=>go(3)} description={<><ul><li>培訓對象為書店／文具同仁</li><li>共計三個場次，時間皆為 13:00–18:00</li></ul><div className="session-list"><span>9/8（二）北區｜誠生訓練教室</span><span>9/17（四）中區｜台中綠園道會議室</span><span>9/22（二）南區｜衛武營教室</span></div><p>為維護課程品質，各店以提報 1 名同仁為原則；如超出名額，請填寫候補名單。</p></>}><StoreTag store={store}/><div className="form-grid"><Field label="參訓同仁員編"><input disabled={data.packaging.none} value={data.packaging.employeeId} placeholder="請輸入員工編號" onChange={e=>setPack({employeeId:e.target.value})}/></Field><Field label="參訓同仁姓名"><input disabled={data.packaging.none} value={data.packaging.name} placeholder="請輸入同仁姓名" onChange={e=>setPack({name:e.target.value})}/></Field><Field label="候補需求（同仁員編＋姓名）" hint="若有多位候補，請以頓號分隔"><textarea disabled={data.packaging.none} value={data.packaging.waitlist} placeholder="例：B06699 王小美" onChange={e=>setPack({waitlist:e.target.value})}/></Field></div><div className="none-row"><Check label="無須新增參訓人員" checked={data.packaging.none} onChange={none=>setPack({none})}/></div><Actions back={()=>go(3)} next={()=>go(5)} nextLabel="繼續，進入職類調查"/></Layout>}
 if(data.step===5){const toggle=(id,cat,val)=>update({roles:{...data.roles,[id]:{...(data.roles[id]||{}),[cat]:val}}});return <Layout step={5} title="書店同仁職類調查" onBack={()=>go(4)} description="請主管填寫門市同仁所屬業管區域，作為後續專業課程調訓依據。選項可複選，請協助補齊每位同仁資料。"><StoreTag store={store}/><div className="role-list">{store?.staff.map(person=><div className="staff-card" key={person.id}><div className="staff-name"><span>{person.name}</span><small>{person.id}</small></div><div className="category-grid">{options.jobCategories.map(cat=><div key={cat}>{<Check label={cat==='生活選物'?'生活選物（戶外、衣飾、美妝、3C 等）':cat} checked={!!data.roles[person.id]?.[cat]} onChange={v=>toggle(person.id,cat,v)}/>} {cat==='其他'&&data.roles[person.id]?.[cat]&&<input className="other" value={data.roles[person.id]?.otherText||''} placeholder="請填寫其他職類" onChange={e=>toggle(person.id,'otherText',e.target.value)}/>}</div>)}</div></div>)}</div><Actions back={()=>go(4)} next={()=>update({submitted:true,step:6})} submit/></Layout>}
 return <Layout step={6} title={mainTitle}><div className="success"><CheckCircle2/><h2>回覆已成功送出</h2><p>感謝您的協助，後續將依排程寄發課程通知。如有其他課程問題，歡迎與學發聯繫。</p></div><div className="contacts"><p><b>鍾才華</b><span>(02) 8789-8880 #207</span><a href="mailto:nancychung@eslite.com">nancychung@eslite.com</a></p><p><b>洪　維</b><span>(02) 8789-8880 #202</span><a href="mailto:weihung@eslite.com">weihung@eslite.com</a></p></div><p className="center-note">如需調整提報名單或回填資訊，請至首頁重新進入問卷，謝謝。</p><Actions next={()=>{reset();window.scrollTo(0,0)}} nextLabel="返回首頁"/></Layout>;
}
function Info({icon:Icon,title,text}){return <div className="info"><Icon/><div><b>{title}</b><span>{text}</span></div></div>}
function StoreTag({store}){return <div className="store-tag"><MapPin size={18}/><span>目前店別</span><b>{store?.id} {store?.name}</b></div>}
